name: malachite-dx
description: Opinionated Fedora Silverblue-based operating system image
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 39

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/bobslept/nerd-fonts/repo/fedora-%OS_VERSION%/bobslept-nerd-fonts-fedora-%OS_VERSION%.repo
    install:
      - iwd
      - podman-docker
      - podman-compose
      - podman-plugins
      - podman-tui
      - podmansh
      - cockpit
      - cockpit-podman
      - cockpit-navigator
      - cockpit-file-sharing
      - cockpit-pcp
      - cockpit-networkmanager
      - cockpit-ostree
      - cockpit-machines
      - cockpit-selinux
      - cockpit-storaged
      - cockpit-system
      - cockpit-ws
      - tailscale
      - tmux
      - fish
      - virt-manager
      - qemu
      - qemu-user-static
      - qemu-user-binfmt
      - libvirt
      - qemu-img
      - ubuntu-nerd-fonts
      - ubuntumono-nerd-fonts
      - vagrant
      - vagrant-libvirt
      - f28-backgrounds-kde
      - f29-backgrounds-kde
      - f30-backgrounds-kde
      - f33-backgrounds-kde
      - butane
      - make
      - waypipe
      - cage
      - genisoimage
      - lxc
      - p7zip
      - waydroid
    remove:
      - wpa_supplicant

  - type: bling
    install:
      - fonts
      - justfiles
      - nix-installer
      - container-tools
      - ublue-update

  - type: script
    scripts:
      - signing.sh
      - networkmanager-realtek.sh
      - starship.sh

  - type: systemd
    system:
      enabled:
        - cockpit.service
        - sshd.service
      disabled:
        - pmie.service
        - pmlogger.service
        - waydroid-container.service
    user:
      enabled:
        - podman.socket
