name: malachite-laptop
description: Opinionated Fedora Silverblue-based operating system image
base-image: ghcr.io/ublue-os/bazzite-deck-gnome
image-version: latest

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    install:
      - iwd
      - podman-compose
      - tmux
      - cockpit
      - cockpit-ws
      - cockpit-podman
      - cockpit-navigator
      - waypipe
      - cage
      - snapd
      - snap-confine
      - waydroid
      - rclone
    remove:
      - wpa_supplicant

  - type: bling
    install:
      - fonts
      - justfiles
      - nix-installer
      - container-tools

  - type: script
    scripts:
      - signing.sh
      - networkmanager-realtek.sh

  - type: systemd
    system:
      enabled:
        - cockpit.service
        - sshd.service
      disabled:
        - waydroid-container.service
    user:
      enabled:
        - podman.socket
