name: malachite-dx
description: Opinionated Fedora Silverblue-based operating system image
base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  - type: files
    files:
      - usr: /usr 

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/bobslept/nerd-fonts/repo/fedora-%OS_VERSION%/bobslept-nerd-fonts-fedora-%OS_VERSION%.repo
    install:
      - iwd
      - podman-docker
      - podman-compose
      - cockpit
      - cockpit-podman
      - cockpit-navigator        
      - cockpit-file-sharing   
      - cockpit-pcp
      - cockpit-networkmanager
      - cockpit-ostree
      - tailscale
      - tmux
      - fish
      - virt-manager
      - qemu
      - qemu-user-static
      - qemu-user-binfmt
      - libvirt
      - qemu-img
      - ubuntu-nerd-fonts
      - ubuntumono-nerd-fonts
    remove:
      - wpa_supplicant

  - type: bling
    install:
      - fonts 
      - justfiles 
      - nix-installer 
      - devpod 

  - type: yafti
    custom-flatpaks: 

  - type: script
    scripts:
      - signing.sh
      - dx-extras.sh
      - networkmanager-realtek.sh
      - nodisplaylink.sh
      - 99-bash-umask.sh
