name: malachite-nvidia
base-image: ghcr.io/ublue-os/bazzite-nvidia
fedora-version: 38
description: Opinionated Fedora Silverblue-based operating system image

scripts:
  pre:
    - autorun.sh
  post:
    - autorun.sh
rpm:
  repos:
  install:
    - python3-pip
    - libadwaita
    - iwd
    - python3-pip
    - libadwaita
    - tmux
    - podman-docker
    - cockpit
    - cockpit-podman
    - cockpit-navigator
    - cockpit-file-sharing
    - tailscale
  remove:
    - wpa_supplicant
firstboot:
  yafti: true
