name: malachite-nvidia
description: Opinionated Fedora Silverblue-based operating system image
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/jstaf/onedriver/repo/fedora-%OS_VERSION%/jstaf-onedriver-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - tailscale
      - tmux
      - waypipe
      - cage
      - rclone
      - onedriver
    remove:

  - type: bling
    install:
      - fonts
      - justfiles
      - nix-installer
      - ublue-update

  - type: script
    scripts:
      - signing.sh
