name: malachite-laptop
description: Opinionated Fedora Silverblue-based operating system image
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/bobslept/nerd-fonts/repo/fedora-%OS_VERSION%/bobslept-nerd-fonts-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/jstaf/onedriver/repo/fedora-%OS_VERSION%/jstaf-onedriver-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - iwd
      - podman-compose
      - tmux
      - cockpit
      - cockpit-ws
      - cockpit-podman
      - cockpit-navigator
      - waypipe
      - cage
      - snapd
      - snap-confine
      - waydroid
      - rclone
      - onedriver
      - yaru-theme
      - ubuntu-nerd-fonts
      - ubuntumono-nerd-fonts
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-gsconnect
      - gnome-shell-extension-blur-my-shell
      - gnome-shell-extension-pop-shell
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-appindicator
    remove:
      - wpa_supplicant

  - type: bling
    install:
      - fonts
      - justfiles
      - nix-installer
      - container-tools
      - laptop
      - ublue-update

  - type: script
    scripts:
      - signing.sh
      - networkmanager-realtek.sh

  - type: systemd
    system:
      enabled:
        - cockpit.service
        - sshd.service
      disabled:
        - waydroid-container.service
    user:
      enabled:
        - podman.socket

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
