name: malachite-nvidia
description: Opinionated Fedora Silverblue-based operating system image
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    install:
      - tmux
      - waypipe
      - cage
      - rclone
      - onedrive
      - fish
    remove:

  - type: bling
    install:
      - justfiles
      - nix-installer
      - ublue-update

  - type: script
    scripts:
      - signing.sh
