name: malachite-dx
description: Opinionated Fedora Silverblue-based operating system image
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 39

modules:
  - type: yafti

  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/bobslept/nerd-fonts/repo/fedora-%OS_VERSION%/bobslept-nerd-fonts-fedora-%OS_VERSION%.repo
    install:
      - podman-compose
      - cockpit
      - cockpit-podman
      - tmux
      - butane
      - make
      - waypipe
      - cage
      - snapd
      - snap-confine
      - waydroid
      - rclone
      - fish
      - ubuntu-nerd-fonts
      - ubuntumono-nerd-fonts
      - onedrive
      - virt-viewer
    remove:

  - type: bling
    install:
      - justfiles
      - nix-installer
      - container-tools
      - ublue-update

  - type: script
    scripts:
      - signing.sh

  - type: systemd
    system:
      disabled:
        - waydroid-container.service
    user:
      enabled:
        - podman.socket

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
