name: malachite
description: Opinionated Fedora Silverblue-based operating system image
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39

modules:
  - type: yafti

  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/bobslept/nerd-fonts/repo/fedora-%OS_VERSION%/bobslept-nerd-fonts-fedora-%OS_VERSION%.repo

      - https://copr.fedorainfracloud.org/coprs/jstaf/onedriver/repo/fedora-%OS_VERSION%/jstaf-onedriver-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - cockpit
      - cockpit-podman
      - cockpit-system
      - cockpit-ws
      - tailscale
      - tmux
      - waypipe
      - cage
      - waydroid
      - rclone
      - onedriver
      - yaru-theme
      - ubuntu-nerd-fonts
      - ubuntumono-nerd-fonts
      - gnome-shell-extension-dash-to-dock
    remove:

  - type: bling
    install:
      - fonts
      - justfiles
      - nix-installer
      - ublue-update

  - type: script
    scripts:
      - signing.sh
      - networkmanager-realtek.sh

  - type: systemd
    system:
      enabled:
        - cockpit.service
        - sshd.service
      disabled:
        - waydroid-container.service
