name: malachite-laptop
description: Opinionated Fedora Silverblue-based operating system image
base-image: ghcr.io/ublue-os/bazzite
image-version: 39

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/bobslept/nerd-fonts/repo/fedora-%OS_VERSION%/bobslept-nerd-fonts-fedora-%OS_VERSION%.repo
    install:
      - iwd
      - cage
      - snapd
      - snap-confine
      - rclone
      - ubuntu-nerd-fonts
      - ubuntumono-nerd-fonts
      - onedrive
      - fish
    remove:
      - wpa_supplicant

  - type: bling
    install:
      - justfiles
      - nix-installer
      - container-tools

  - type: script
    scripts:
      - signing.sh
      - networkmanager-realtek.sh

  - type: systemd
    system:
      disabled:
        - waydroid-container.service
    user:
      enabled:
        - podman.socket

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
