name: malachite-nvidia
description: Opinionated Fedora Silverblue-based operating system image
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
    install:
      - iwd
      - podman-docker
      - podman-compose
      - cockpit
      - cockpit-podman
      - cockpit-navigator
      - cockpit-file-sharing
      - cockpit-pcp
      - cockpit-networkmanager
      - cockpit-ostree
      - tailscale
      - tmux
    remove:
      - wpa_supplicant

  - type: bling
    install:
      - fonts
      - justfiles
      - nix-installer

  - type: script
    scripts:
      - networkmanager-realtek.sh
      - nodisplaylink.sh
      - 99-bash-umask.sh
