name: malachite
description: Opinionated Fedora Silverblue-based operating system image
base-image: ghcr.io/ublue-os/bazzite
image-version: 39

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
    install:
      - cage
      - rclone
      - fish
      - onedrive
    remove:

  - type: bling
    install:
      - justfiles
      - nix-installer

  - type: script
    scripts:
      - signing.sh

  - type: systemd
    system:
      disabled:
        - waydroid-container.service
        - displaylink.service
        - bazzite-hardware-setup.service