name: malachite-dx
base-image: ghcr.io/ublue-os/bazzite
fedora-version: 38
description: Opinionated Fedora Silverblue-based operating system image

scripts:
  pre:
    - autorun.sh
  post:
    - autorun.sh
    - dx-extras.sh
rpm:
  repos:
    - https://copr.fedorainfracloud.org/coprs/bobslept/nerd-fonts/repo/fedora-%FEDORA_VERSION%/bobslept-nerd-fonts-fedora-%FEDORA_VERSION%.repo
  install:
    - python3-pip
    - libadwaita
    - iwd
    - podman-docker
    - podman-compose
    - cockpit
    - cockpit-podman
    - cockpit-navigator
    - cockpit-file-sharing
    - cockpit-pcp
    - cockpit-networkmanager
    - cockpit-ostree
    - tailscale
    - fish
    - virt-manager
    - qemu
    - qemu-user-static
    - qemu-user-binfmt
    - libvirt
    - qemu-img
    - tmux
    - ubuntu-nerd-fonts
    - ubuntumono-nerd-fonts
  remove:
    - wpa_supplicant
firstboot:
  yafti: true
