name: malachite-dx
description: Opinionated Fedora Silverblue-based operating system image
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: 39

modules:
  - type: yafti

  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/bobslept/nerd-fonts/repo/fedora-%OS_VERSION%/bobslept-nerd-fonts-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/jstaf/onedriver/repo/fedora-%OS_VERSION%/jstaf-onedriver-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - podman-compose
      - cockpit
      - cockpit-podman
      - cockpit-navigator
      - cockpit-file-sharing
      - cockpit-pcp
      - cockpit-networkmanager
      - cockpit-ostree
      - cockpit-selinux
      - cockpit-storaged
      - cockpit-system
      - cockpit-ws
      - tmux
      - f28-backgrounds-gnome
      - f29-backgrounds-gnome
      - f30-backgrounds-gnome
      - f33-backgrounds-gnome
      - butane
      - make
      - waypipe
      - cage
      - snapd
      - snap-confine
      - waydroid
      - lzip
      - vagrant
      - vagrant-libvirt
      - virt-manager
      - virt-bootstrap
      - virt-top
      - virt-backup
      - virt-install
      - virt-top
      - virt-what
      - virt-v2v
      - virt-p2v
      - cockpit-machines
      - gnome-boxes
      - rclone
      - onedriver
      - yaru-theme
      - ubuntu-nerd-fonts
      - ubuntumono-nerd-fonts
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-gsconnect
      - gnome-shell-extension-blur-my-shell
      - gnome-shell-extension-pop-shell
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-appindicator
    remove:

  - type: bling
    install:
      - fonts
      - justfiles
      - nix-installer
      - container-tools
      - ublue-update

  - type: script
    scripts:
      - signing.sh

  - type: systemd
    system:
      enabled:
        - cockpit.service
        - sshd.service
      disabled:
        - waydroid-container.service
    user:
      enabled:
        - podman.socket

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
