name: malachite-nvidia
description: Opinionated Fedora Silverblue-based operating system image
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
    install:
      - iwd
      - tailscale
      - tmux
      - waypipe
      - cage
      - rclone
    remove:
      - wpa_supplicant

  - type: bling
    install:
      - fonts
      - justfiles
      - nix-installer

  - type: script
    scripts:
      - signing.sh
      - networkmanager-realtek.sh

  - type: systemd
    system:
      enabled:
      disabled:
        - displaylink.service
