name: malachite-nvidia
description: Opinionated Fedora Silverblue-based operating system image
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: 39

modules:
  - type: files
    files:
      - usr: /usr
      - laptop: /usr

  - type: rpm-ostree
    repos:
    install:
      - iwd
      - podman-docker
      - podman-compose
      - cockpit
      - cockpit-podman
      - cockpit-navigator
      - cockpit-file-sharing
      - cockpit-pcp
      - cockpit-networkmanager
      - cockpit-ostree
      - cockpit-machines
      - cockpit-selinux
      - cockpit-storaged
      - cockpit-system
      - cockpit-ws
      - tailscale
      - tmux
      - waypipe
      - cage
    remove:
      - wpa_supplicant

  - type: bling
    install:
      - fonts
      - justfiles
      - nix-installer
      - ublue-update
      - laptop

  - type: script
    scripts:
      - signing.sh
      - networkmanager-realtek.sh

  - type: systemd
    system:
      enabled:
        - cockpit.service
        - sshd.service
      disabled:
        - pmie.service
        - pmlogger.service
