name: malachite-nvidia
description: Opinionated Fedora Silverblue-based operating system image
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    install:
      - cage
      - fish
    remove:

  - type: bling
    install:
      - justfiles
      - nix-installer

  - type: script
    scripts:
      - signing.sh

  - type: systemd
    system:
      disabled:
        - bazzite-hardware-setup.service
        - displaylink.service
