name: malachite
description: Opinionated Fedora Silverblue-based operating system image
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: latest

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/bobslept/nerd-fonts/repo/fedora-%OS_VERSION%/bobslept-nerd-fonts-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/jstaf/onedriver/repo/fedora-%OS_VERSION%/jstaf-onedriver-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - podman-compose
      - tmux
      - cockpit
      - cockpit-ws
      - cockpit-podman
      - cockpit-navigator
      - waypipe
      - cage
      - snapd
      - snap-confine
      - waydroid
      - rclone
      - onedriver
      - yaru-theme
      - ubuntu-nerd-fonts
      - ubuntumono-nerd-fonts
    remove:

  - type: bling
    install:
      - justfiles
      - nix-installer

  - type: script
    scripts:
      - signing.sh

  - type: systemd
    system:
      enabled:
        - cockpit.service
        - sshd.service
      disabled:
        - displaylink.service
        - pmie.service
        - pmlogger.service
        - waydroid-container.service
