bling:
  @just --unstable -f /usr/share/ublue-os/just/bling.just

setup:
  @just --unstable -f /usr/share/ublue-os/just/setup.just

skel-to-home:
  rsync -avh /etc/skel "$HOME"

yafti:
  rm -r "$HOME/.config/yafti"
  yafti /usr/share/ublue-os/malachite/yaftifile.yml

update-yadm:
  cd $HOME/.local/share/yadm-clone && git pull

fix-libvirt:
  sudo --askpass sh -c "groupadd --system libvirt && \
  groupadd --system qemu && \
  usermod -a -G libvirt $USER && \
  usermod -a -G qemu $USER"

push-to-registry IMAGE:
	podman push localhost/{{IMAGE}}:latest localhost:5000/{{IMAGE}}:latest

registry-local:
	echo -e '[[registry]]\nlocation = "localhost:5000"\ninsecure = true' > /etc/containers/registries.conf.d/local.conf

registry-create:
	podman run -d -p 5000:5000 --restart=always --name registry registry:2

registry-start:
	podman start registry