title: Welcome to Malachite
properties:
  mode: "run-on-change"
screens:
  first-screen:
    source: yafti.screen.title
    values:
      title: "Welcome to Malachite"
      icon: "/path/to/icon"
      description: |
        This guided installer will help you get started with your new system.
  configure-system:
    source: yafti.screen.package
    values:
      title: Configure Malachite System
      show_terminal: true
      package_manager: yafti.plugin.run
      groups:
        Nimbus:
          description: Development toolbox meant for coding!
          default: false
          condition:
            run: distrobox list | grep -v nimbus
          packages:
            - Setup Nimbus container: just-malachite setup nimbus
        Nix Package Manager:
          description: Nix is a powerful package manager for Linux and other Unix systems that makes package management reliable and reproducible
          default: false
          packages:
            - Install Nix Package Support: just-malachite setup nix
        Waydroid:
          description: Android support with GApps, ARM translation, and Widevine out of the box
          default: false
          packages:
            - Setup waydroid: just-malachite setup waydroid
            - Setup waydroid-only session: just setup waydroid-session
            - Setup shortcuts: just-malachite setup waydroid-shortcut
        Remote:
          description: Sets up proper remote access to this system!
          default: false
          packages:
            - Setup Remotes: just-malachite setup remotes
        Dotfiles:
          description: Sets up my dotfiles and applies them directily to your system
          default: false
          packages:
            - Setup: just-malachite setup dotfiles
        Webapp Manager:
          description: Sets up a webapp manager!
          default: false
          packages:
            - Setup: just-malachite setup webapp-manager
        Positivo Touch Screen:
          description: Adds udev rules for Positivo c464c-like laptops touchscreens
          default: false
          packages:
            - Setup: just-malachite setup positivo-touchscreen
        Enable Libvirtd Groups:
          description: Adds libvirtd and qemu groups to your user for usage with virt-manager
          default: false
          packages:
            - Setup: just-malachite fix-libvirt
  can-we-modify-your-flatpaks:
    source: yafti.screen.consent
    values:
      title: Welcome, Traveler!
      condition:
        run: flatpak remotes --columns=name | grep fedora
      description: |
        We have detected the limited, Fedora-provided Flatpak remote on your system, whose applications are usually missing important codecs and other features. This step will therefore remove all basic Fedora Flatpaks from your system! We will instead switch all core Flatpak applications over to the vastly superior, unfiltered Flathub. If you don't want to do this, simply exit this installer.
      actions:
        - run: flatpak remote-delete --system --force fedora
        - run: flatpak remote-delete --user --force fedora
        - run: flatpak remove --system --noninteractive --all
        - run: flatpak remote-add --if-not-exists --system flathub https://flathub.org/repo/flathub.flatpakrepo
        - run: flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
  check-system-flathub:
    source: yafti.screen.consent
    values:
      title: Missing Flathub Repository (System)
      condition:
        run: flatpak remotes --system --columns=name | grep flathub | wc -l | grep '^0$'
      description: |
        We have detected that you don't have Flathub's repository on your system. We will now add that repository to your system-wide list.
      actions:
        - run: flatpak remote-add --if-not-exists --system flathub https://flathub.org/repo/flathub.flatpakrepo
  check-user-flathub:
    source: yafti.screen.consent
    values:
      title: Missing Flathub Repository (User)
      condition:
        run: flatpak remotes --user --columns=name | grep flathub | wc -l | grep '^0$'
      description: |
        We have detected that you don't have Flathub's repository on your current user account. We will now add that repository to your account.
      actions:
        - run: flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
  applications:
    source: yafti.screen.package
    values:
      title: Application Installer
      show_terminal: true
      package_manager: yafti.plugin.flatpak
      package_manager_defaults:
        user: true
        system: false
      groups:
        System GNOME Apps:
          description: Core system applications for GNOME
          default: false
          packages:
            - Calculator: org.gnome.Calculator
            - Calendar: org.gnome.Calendar
            - Snapshot: org.gnome.Snapshot
            - Clocks: org.gnome.clocks
            - Connections: org.gnome.Connections
            - Disk Usage Analyzer: org.gnome.baobab
            - Document Viewer: org.gnome.Evince
            - Extension Manager: com.mattjakeman.ExtensionManager
            - Image Viewer: org.gnome.Loupe
            - File Previewr: org.gnome.NautilusPreviewer
            - Text Editor: org.gnome.TextEditor
            - Video Player: io.github.celluloid_player.Celluloid
            - Music Player: com.github.neithern.g4music
            - Weather: org.gnome.Weather
            - Logs: org.gnome.Logs
        GNOME Extras:
          description: Extra GNOME applications
          default: false
          packages:
            - RSS Reader (NewsFlash): io.gitlab.news_flash.NewsFlash
            - Authenticator: com.belmoussaoui.Authenticator
            - Photo Organizer: org.gnome.Shotwell
            - Music Library Player: org.gnome.Lollypop
            - GTK4 Theme Customizer: com.github.GradienceTeam.Gradience
            - Login Screen Manager: io.github.realmazharhussain.GdmSettings
            - DConf Editor: ca.desrt.dconf-editor
            - Podcasts Player: org.gnome.Podcasts
        KDE System Apps:
          description: Core system applications for KDE
          default: true
          packages:
            - Video Viewer (VLC): org.vlc.VLC
            - Music Player (Elisa): org.kde.elisa
            - Image Viewer: org.kde.koko
            - Pipewire Viewer (QPWGraph): org.rncbc.qpwgraph
            - Document Viewer (Okular): org.kde.okular
            - Terminal Emulator (Yakuake): org.kde.yakuake
            - Clock: org.kde.kclock
            - Weather: org.kde.kweather
            - Calculator (Kalk): org.kde.kalk
            - Camera (Kamoso): org.kde.kamoso
            - Book Reader (Arianna): org.kde.arianna
        KDE Extras:
          description: Core system applications for KDE
          default: false
          packages:
            - Authenticator (Keysmith): org.kde.keysmith
            - RSS Reader (Alligator): org.kde.alligator
            - Password Manager (KeepassXC): org.keepassxc.KeePassXC
            - Podcasts (Kasts): org.kde.kasts
            - Video Editor (Kdenlive): org.kde.kdenlive
            - Krita: org.kde.krita
            - Matrix (Neochat): org.kde.neochat
            - Mastodon (Tokodon): org.kde.tokodon
            - Music Player (Vvave): org.kde.vvave
            - Kontact: org.kde.kontact
            - KMail: org.kde.kmail
            - Jukebox (JuK): org.kde.juk
            - Kontrast: org.kde.kontrast
            - Media Player (Haruna): org.kde.haruna
        System Apps:
          description: System applications for all desktop environments.
          default: true
          packages:
            - Permission Manager: com.github.tchx84.Flatseal
            - Audio Routing: org.pipewire.Helvum
            - Firmware Manager: org.gnome.Firmware
            - System Inspector: io.github.nokse22.inspector
            - System Monitor: io.missioncenter.MissionCenter
            - Network Inspector: org.gabmus.whatip
            - ISO Image Writer: org.kde.isoimagewriter
            - Flatpak Cleaner: io.github.giantpinkrobots.flatsweep
            - Backup Manager: com.borgbase.Vorta
        System Extras:
          description: System applications for all desktop environments.
          default: false
          packages:
            - EasyEffects: com.github.wwmm.easyeffects
            - Download Manager: org.kde.kget
            - Syncthing GTK: me.kozec.syncthingtk
            - Bitwarden: com.bitwarden.desktop
            - Fedora Media Writer: org.fedoraproject.MediaWriter
            - Bitwarden: com.bitwarden.desktop
            - Cockpit Client: org.cockpit_project.CockpitClient
            - Youtube Downloader: org.nickvision.tubeconverter
            - Youtube Player: io.gitlab.zehkira.Monophony
            - Youtube Music Client (AudioTube): org.kde.audiotube
            - Youtube Client (PlasmaTube): org.kde.plasmatube
            - Key Manager: org.gnome.seahorse.Application
            - Music Metadata Tagger: org.nickvision.tagger
            - Pomodoro Timer: org.gnome.Solanum
            - Remote Viewer (KRDC): org.kde.krdc
            - Time Tracker (KTimeTracker): org.kde.ktimetracker
            - QBittorrent: org.qbittorrent.qBittorrent
            - Transmission: com.transmissionbt.Transmission
            - Fragments: de.haeckerfelix.Fragments
            - Delunge: org.deluge_torrent.deluge
            - Backup Manager (PikaBackup): org.gnome.World.PikaBackup
        Web Browsers:
          description: Additional browsers to complement or replace Firefox.
          default: false
          packages:
            - Firefox: org.mozilla.firefox
            - Librewolf: io.gitlab.librewolf-community
            - Chromium: org.chromium.Chromium
            - Ungoogled Chromium: com.github.Eloston.UngoogledChromium
            - Brave: com.brave.Browser
            - Google Chrome: com.google.Chrome
            - Microsoft Edge: com.microsoft.Edge
            - Opera: com.opera.Opera
        Gaming:
          description: "Rock and Stone!"
          default: false
          packages:
            - RetroDeck: net.retrodeck.retrodeck
            - Minetest: net.minetest.Minetest
            - OpenArena: ws.openarena.OpenArena
            - Frogatto: com.frogatto.Frogatto
            - Cave Story NX: com.gitlab.coringao.cavestory-nx
            - Pekka Kana: net.pistegamez.PekkaKana2
            - 0 AD: com.play0ad.zeroad
            - Sonic Robo Blast: org.srb.SRB
            - Roblox (Launcher): io.github.vinegarhq.Vinegar
            - Veloren (Launcher): net.veloren.airshipper
            - Retroarch: org.libretro.RetroArch
            - Lutris: net.lutris.Lutris
            - Bottles: com.usebottles.bottles
            - Discord: com.discordapp.Discord
            - Cardriges: hu.kramo.Cartridges
            - Heroic Games Launcher: com.heroicgameslauncher.hgl
            - Steam: com.valvesoftware.Steam
            - Gamescope (Utility): org.freedesktop.Platform.VulkanLayer.gamescope
            - MangoHUD (Utility): org.freedesktop.Platform.VulkanLayer.MangoHud//22.08
            - SteamTinkerLaunch (Utility): com.valvesoftware.Steam.Utility.steamtinkerlaunch
            - Proton Updater for Steam: net.davidotek.pupgui2
        Office:
          description: Boost your productivity.
          default: false
          packages:
            - LibreOffice: org.libreoffice.LibreOffice
            - OnlyOffice: org.onlyoffice.desktopeditors
            - Setzer (LaTeX): org.cvfosammmm.Setzer
            - Kile (LaTeX): org.kde.kile
            - Thunderbird Email: org.mozilla.Thunderbird
            - Evolution: org.gnome.Evolution
            - GhostWriter: io.github.wereturtle.ghostwriter
            - Apostrophe: org.gnome.gitlab.somas.Apostrophe
            - Obsidian: md.obsidian.Obsidian
            - Logseq: com.logseq.Logseq
            - Zim: org.zim_wiki.Zim
        Making Content:
          description: Make content for the Internet.
          default: false
          packages:
            - Penpot Desktop: com.sudovanilla.penpot-desktop
            - Frog: com.github.tenderowl.frog
            - DigiKam: org.kde.digikam
            - Halftone: io.github.tfuxu.Halftone
            - Contrast: org.gnome.design.Contrast
            - Godot Engine: org.godotengine.Godot
            - VideoTrimmer: org.gnome.gitlab.YaLTeR.VideoTrimmer
            - Pixelorama: com.orama_interactive.Pixelorama
            - Vpuppr: pro.vpup.vpuppr
            - Godot: org.godotengine.Godot
            - Audacity: org.audacityteam.Audacity
            - Inkscape: org.inkscape.Inkscape
            - Emblem: org.gnome.design.Emblem
            - Contrast: org.gnome.design.Contrast
            - Elastic (Animations): app.drey.Elastic
            - Letter Press: io.gitlab.gregorni.ASCIIImages
            - Icon Library: org.gnome.design.IconLibrary
            - Identity: org.gnome.gitlab.YaLTeR.Identity
            - Footage: io.gitlab.adhami3310.Footage
            - Upscaler: io.gitlab.theevilskeleton.Upscaler
            - EarTag: app.drey.EarTag
            - KdenLive: org.kde.Kdenlive
            - Krita: org.kde.Krita
            - Ardour: org.ardour.Ardour
            - LMMS: io.lmms.LMMS
            - LibreSprite: com.github.libresprite.LibreSprite
            - OBS Studio: com.obsproject.Studio
            - VkCapture for OBS: com.obsproject.Studio.OBSVkCapture
            - Gstreamer for OBS: com.obsproject.Studio.Plugin.Gstreamer
            - Gstreamer VAAPI for OBS: com.obsproject.Studio.Plugin.GStreamerVaapi
            - Boatswain for Streamdeck: com.feaneron.Boatswain
        Development:
          description: Tools for development
          default: false
          packages:
            - Kleopatra: org.kde.kleopatra
            - Profiler (KCacheGrind): org.kde.kcachegrind
            - Kompare: org.kde.kompare
            - Okteta: org.kde.okteta
            - Git Notifier: com.mardojai.ForgeSparks
            - GitG: org.gnome.gitg
            - Android Studio: com.google.AndroidStudio
            - Cambalache: ar.xjuan.Cambalache
            - Kdevelop: org.kde.Kdevelop
            - Gnome Builder: org.gnome.Builder
            - VSCode: com.visualstudio.code
            - VSCodium: com.vscodium.codium
            - Pods: com.github.marhkb.Pods
            - Podman Desktop: io.podman_desktop.PodmanDesktop
            - Meld: org.gnome.meld
            - Github Desktop: io.github.shiftey.Desktop
            - Bavarder: io.github.Bavarder.Bavarder
            - Processing IDE: org.processing.processingide
            - GuiScrCpy: in.srev.guiscrcpy
  final-screen:
    source: yafti.screen.title
    values:
      title: "All done!"
      icon: "/path/to/icon"
      links:
        - "Install More Applications":
          run: /usr/bin/gnome-software
        - "Website":
          run: /usr/bin/xdg-open https://universal-blue.org
        - "This images source":
          run:
        - "Join the Discord Community":
          run: /usr/bin/xdg-open https://discord.gg/XjG48C7VHx
      description: |
        Thank you for trying Malachite, we hope you enjoy it!
